server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.php index.html;

    location ~ ^/(css|js|img|fonts)/(.*)$ {
        alias /var/www/html/public/$1/$2;
        access_log off;
        expires max;
    }
    
    location = /robots.txt {
        alias /var/www/html/public/robots.txt;
    }

    location / {
        try_files $uri $uri.php $uri/ /index.php?$query_string;
    }

    location = /admin {
        rewrite ^ /admin/admin.php last;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\. {
        deny all;
    }
}